version: '3'

services:
  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    depends_on:
      - mongo

  # MongoDB
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

